### ISSUE TITLE
likely double call in -shuffle

### ISSUE THREAD

**Issue by MCOfficer** [EndlessSkyCommunity/EndlessSky-Discord-Bot#120]
```
net.dv8tion.jda.core.exceptions.ErrorResponseException: 10008: Unknown Message
        at net.dv8tion.jda.core.exceptions.ErrorResponseException.create(ErrorResponseException.java:145)
        at net.dv8tion.jda.core.requests.Request.onFailure(Request.java:91)
        at net.dv8tion.jda.core.entities.MessageChannel$2.handleResponse(MessageChannel.java:1004)
        at net.dv8tion.jda.core.requests.Request.handleResponse(Request.java:178)
        at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:202)
        at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:112)
        at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:95)
        at net.dv8tion.jda.core.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:312)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at net.dv8tion.jda.core.requests.RateLimiter$RateLimitThreadFactory.lambda$newThread$0(RateLimiter.java:129)
        at java.lang.Thread.run(Thread.java:748)
```
the message gets deleted as intended, so there's likely a doublecall of Message#delete.

**Comment by MCOfficer** [comment]
since the code has been revamped (#144) i have no reason to believe this still exists.
