### ISSUE TITLE
`-show` can exceed the character limit

### ISSUE THREAD

**Issue by MCOfficer** [EndlessSkyCommunity/EndlessSky-Discord-Bot#154]
e.g.

![grafik](https://user-images.githubusercontent.com/22377202/55987360-ad63ce00-5ca1-11e9-9b6a-4f703e762d10.png)
Results in
```
20:26:45.580 [JDA MainWS-ReadThread] ERROR net.dv8tion.jda.core.JDA - One of the EventListeners had an uncaught exception
java.lang.IllegalStateException: Cannot build a Message with more than 2000 characters. Please limit your input.
        at net.dv8tion.jda.core.MessageBuilder.build(MessageBuilder.java:816)
        at me.mcofficer.james.commands.lookup.Show.createShowMessage(Show.java:49)
        at me.mcofficer.james.commands.lookup.Show.lambda$execute$0(Show.java:37)
        at com.jagrosh.jdautilities.menu.OrderedMenu.lambda$waitGeneric$3(OrderedMenu.java:231)
        at com.jagrosh.jdautilities.commons.waiter.EventWaiter$WaitingEvent.attempt(EventWaiter.java:287)
        at com.jagrosh.jdautilities.commons.waiter.EventWaiter.lambda$onEvent$2(EventWaiter.java:244)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at com.jagrosh.jdautilities.commons.waiter.EventWaiter.onEvent(EventWaiter.java:244)
        at net.dv8tion.jda.core.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:84)
        at net.dv8tion.jda.core.handle.MessageReactionHandler.onAdd(MessageReactionHandler.java:156)
        at net.dv8tion.jda.core.handle.MessageReactionHandler.handleInternally(MessageReactionHandler.java:126)
        at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:37)
        at net.dv8tion.jda.core.requests.WebSocketClient.onDispatch(WebSocketClient.java:1069)
        at net.dv8tion.jda.core.requests.WebSocketClient.onEvent(WebSocketClient.java:929)
        at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:908)
        at net.dv8tion.jda.core.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1101)
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368)
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:270)
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:990)
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:749)
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)

```

**Comment by Anarchist2** [comment]
Until we can properly solve this issue, there should be some sort of message that pops up when this happens to alert the bot user that the current item can't be shown by -show due to being too long.
